#configuration file for holding runtime configurations and parameters

# ---Pipeline Execution Parameters---
exec:
  #name of the output directory
  outdir: 'p1_veroSTAT1KO'
  #name of the logfile
  logfile: 'p1_veroSTAT1KO_logs.log'
  #list of reference sequences used for mapping 
  #(brackets[] indicate more than one reference. 
  #If used, inputs must be in a subfolder named for the reference sequence)
  referenceSequences: ["p1_veroSTAT1KO.fasta"]
  #minimum average depth after mapping
  minimumAverageDepth: 100
  #minimum percent of reference bases covered
  percentRefCovered: 100

  # ---replicate variables---
  #samples in replicate
  replicates: False
  #Notation for sample replicates: SampleX_R1.fasta 
  #eg. if your fastq is H1N1.1_R1, please write "Sample.1_R1"
  # or if fastq is H1N1Rep1_R1, please write "SampleRep1_R1"
  # or if fastq is r1_ZW456_R1, please write "r1_Sample_R1"
  replicateNotation: "Sample_rep1_R1"
  #variant calling using 'Varscan' or 'RePlow' or 'Compare' (only three options). 
  #'Compare' will run both and produce an excel file that places the results side by side. 
  #'Compare' does not work with more than one set of replicates.
  #***Compare is not currently supported.***
  callSNPs: 'Varscan'
  
  # ---pipeline functions---
  #filter out samples which don't meet minimum coverage threshold
  coverageFilter: False
  #consensus generation using VarScan
  generateConsensus: True
  #consensus generation for all samples of given reference using VarScan
  generatePopConsensus: True
  #map the reads to the consensus sequence using bowtie2
  mapToConsensus: False
  #annotate SNPs with Louise Moncla's custom annotator
  annotateSNPs: True
  #use SNPgenie to derive population statistics #we'll do this separately
  SNPgenier: False

  # ---data cleaning---
  #use unpaired reads, or only paired reads
  unpaired: False

  #coverage depth normalization using seqtk
  #normalize coverage across the sam or bam file by randomly downsampling to a set number of reads
  normalizeCoverage: False
  totalReads: 200000

# ---Quality Trimming Parameters---
trimmomatic:
  #remove adapter sequences from the reads
  removeAdapters: False
  #adapter file name included in trimmomatic
  adaptersFileName: "Nextera_XT_adapter.fa"
  #paired end reads
  paired: True
  #minmial read length
  minlength: 100
  #sliding window size for quality trim
  windowSize: 5
  #quality threashold for trim in sliding window
  qscore: 30

# ---Single Nucelotide Polymorhpism Calling Parameters---
snpcalling:
  #minimum coverage for SNP
  minCoverage: 100
  #minimum quality for SNP
  snpQualityThreshold: 30
  #minimum frequency for SNP
  snpFrequency: 0.01
  #minimum frequency for a consensus SNP in generating the consensus sequence
  consensusFrequency: 0.5

#Replow-specific settings
replow_settings:
  #minimum mapping quality
  mapquality: 30
  #influenza mutation rate
  mutrate:  4E-05
  
  #Oh man this is such an apples-to-oranges comparison. The fundamental question being asked is "What is the pre-test probability of any given nucleotide being different than the reference sequence?"
  #This number is derived in cancer from looking at the number of mutation per Mb in the tumor compared to somatic mutations. You can't really do that in viruses.
  #The closest analogy would be looking at the number of SNPs present in one ferret after infection with a standard strain. I don't know if people have done this,
  #Because mutation rate/replication cycle is so much easier to do.
  #This paper more recently estimated 1.4x10^-5 mutations/site/48hrs in influenza A, which seems like a reasonable estimate for a course of influenza.
  #source: Nobusawa E, Katsuhiki S. "Comparison of the Mutation Rates of Human Influenza A and B Viruses". Journal of Virology Mar 2006, 80 (7) 3675-3678; DOI: 10.1128/JVI.80.7.3675-3678.2006
  #Ultimately I don't know how much this will affect our calls, but it seems reasonable to try to estimate it accurately.
  #Another way of going about it would be this: Estimates seem to range around 5E-03 mut/site/year, so a 3-7 day infection should cause 4E-5 to 1E-4 mut/site/infection. 
  #Combine the two, and 4E-05 seems reasonable.
  #mut/site/year estimate source: Rubing Chen, Edward C. Holmes, Avian Influenza Virus Exhibits Rapid Evolutionary Dynamics, Molecular Biology and Evolution, Volume 23, Issue 12, December 2006, Pages 2336–2341, https://doi.org/10.1093/molbev/msl102

# ---Post-SNP population analysis---
postprocessing:
  #location of gtf file
  gtfFileNames: ["p1_veroSTAT1KO.gtf"]
  #minimum frequency of SNPs to be considered by SNPGenie
  minSNPfreq: 0.01
  #sliding window size for SNPGenie analysis (# of codons)
  slidingwindow: 50